"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""


class Downloads:
    """
    @type r_id: int | None
    @type d_date: str | None
    @type d_downloads: int | None
    """

    def __init__(self):
        self.r_id = None  # t(r_id)
        self.d_date = None  # t(d_date)
        self.d_downloads = None  # t(d_downloads)
