"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""


class Downloads:
    """
    :type r_id: int | None
    :type d_date: str | None
    :type d_downloads: int | None
    """

    def __init__(self):
        self.r_id = None  # t
        self.d_date = None  # t
        self.d_downloads = None  # t
