"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""


class Release:
    """
    @type r_id: int | None
    @type r_name: str | None
    """

    def __init__(self):
        self.r_id = None  # t(r_id)
        self.r_name = None  # t(r_name)
