"""
Code generated by a tool. DO NOT EDIT.
https://sqldalmaker.sourceforge.net/
"""


class ReleaseData:
    """
    :type r_id: int | None
    :type r_name: str | None
    """

    def __init__(self):
        self.r_id = None  # t
        self.r_name = None  # t
