"""
This code was generated by a tool. Don't modify it manually.
http://sqldalmaker.sourceforge.net
"""


class Task:
    """
    @type t_id: int | None
    @type g_id: int | None
    @type t_priority: int | None
    @type t_date: str | None
    @type t_subject: str | None
    @type t_comments: str | None
    @type t_double: float | None
    @type t_decimal: float | None
    @type t_numeric: float | None
    @type t_real: float | None
    """

    def __init__(self):
        self.t_id = None  # t(t_id)
        self.g_id = None  # t(g_id)
        self.t_priority = None  # t(t_priority)
        self.t_date = None  # t(t_date)
        self.t_subject = None  # t(t_subject)
        self.t_comments = None  # t(t_comments)
        self.t_double = None  # t(t_double)
        self.t_decimal = None  # t(t_decimal)
        self.t_numeric = None  # t(t_numeric)
        self.t_real = None  # t(t_real)
