package com.sdm.thesaurus.dto;

// Code generated by a tool. DO NOT EDIT.
// https://sqldalmaker.sourceforge.net/

public class RelatedWord  {

    private java.lang.Object rgPartOfSpeech;  // q
    private java.lang.Object rgOrder;  // q
    private java.lang.Object rgwId;  // q
    private java.lang.Object rgId;  // q
    private java.lang.Object rgwWord;  // q
    private java.lang.Object rgwNote;  // q
    private java.lang.Object rgwOrder;  // q

    public java.lang.Object getRgPartOfSpeech() {
        return this.rgPartOfSpeech;
    }

    public void setRgPartOfSpeech(java.lang.Object rgPartOfSpeech) {
        this.rgPartOfSpeech = rgPartOfSpeech;
    }

    public java.lang.Object getRgOrder() {
        return this.rgOrder;
    }

    public void setRgOrder(java.lang.Object rgOrder) {
        this.rgOrder = rgOrder;
    }

    public java.lang.Object getRgwId() {
        return this.rgwId;
    }

    public void setRgwId(java.lang.Object rgwId) {
        this.rgwId = rgwId;
    }

    public java.lang.Object getRgId() {
        return this.rgId;
    }

    public void setRgId(java.lang.Object rgId) {
        this.rgId = rgId;
    }

    public java.lang.Object getRgwWord() {
        return this.rgwWord;
    }

    public void setRgwWord(java.lang.Object rgwWord) {
        this.rgwWord = rgwWord;
    }

    public java.lang.Object getRgwNote() {
        return this.rgwNote;
    }

    public void setRgwNote(java.lang.Object rgwNote) {
        this.rgwNote = rgwNote;
    }

    public java.lang.Object getRgwOrder() {
        return this.rgwOrder;
    }

    public void setRgwOrder(java.lang.Object rgwOrder) {
        this.rgwOrder = rgwOrder;
    }
}